// Auto-generated by uer — do not edit
#pragma once

#include <cstdint>
#include <cstring>
#include <cstddef>

struct Buffer {
    uint8_t const* ptr;
    uintptr_t len;
};

enum class ArgTag : uint8_t {
    Unit, Bool, U8, I8, U16, I16, U32, I32, U64, I64, F32, F64, F64CPtr, F64Ptr, USize, ISize, Void, CPtr, Ptr, Buf, String
};

union ArgType {
    bool bool_val;
    uint8_t u8_val;
    int8_t i8_val;
    uint16_t u16_val;
    int16_t i16_val;
    uint32_t u32_val;
    int32_t i32_val;
    uint64_t u64_val;
    int64_t i64_val;
    float f32_val;
    double f64_val;
    double const* f64cptr_val;
    double* f64ptr_val;
    uintptr_t usize_val;
    size_t isize_val;
    void* void_val;
    void const* cptr_val;
    void* ptr_val;
    Buffer buf_val;
};

struct Argument {
    ArgTag tag;
    ArgType value;
};

struct Return {
    bool is_some;
    Argument value;
};

struct UERustRsApi {
    Return (*rinvoke)(uint16_t rmethod_id, Argument const* args, size_t len);
};

struct UERustCApi {
    Return (*invoke)(uint16_t method_id, Argument const* args, size_t len);
};

typedef UERustRsApi(*UERustGetRsApiFn)(UERustCApi);
UERustRsApi& GetUERustRsApi_0();
UERustCApi __uerust_get_capi_0();