// Auto-generated by uer — do not edit
#include "bindings.h"
#include <cstring>
#include "UERustModule.h"

Return __uerust_invoke_(uint16_t method_id, Argument const* args, size_t len) {
    FUERustModule::Get().Invoke(method_id, args, len);
    return Return { .is_some = false };
}

UERustCApi __uerust_get_capi_0() {
    return UERustCApi {
        .invoke = __uerust_invoke_
    };
}
